# Generated by Django 5.0.4 on 2024-04-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(default=int, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
