# Generated by Django 5.0.4 on 2024-04-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=int, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
