# Generated by Django 5.0.4 on 2024-04-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='certificate',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
