# Generated by Django 5.0.4 on 2024-04-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_request', models.IntegerField()),
                ('user_target', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], max_length=20)),
            ],
        ),
    ]
