# Generated by Django 5.0.4 on 2024-04-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='certificate',
        ),
    ]
